name: Build workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-and-check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Use Node.js 17.8.x
        uses: actions/setup-node@main
        with:
          node-version: 17.8.x
      - name: Build Docusaurus website
        run: |
          npm install
          npm run build
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.5.0
        with:
          fail: true
            # For parameter description, see https://github.com/lycheeverse/lychee#commandline-parameters
            # -E, --exclude-all-private    Exclude all private IPs from checking.
            # -i, --insecure               Proceed for server connections considered insecure (invalid TLS)
            # -n, --no-progress            Do not show progress bar.
            # -t, --timeout <timeout>      Website timeout in seconds from connect to response finished [default:20]
            # --max-concurrency <max-concurrency>    Maximum number of concurrent network requests [default: 128]
            # -a --accept <accept>                      Comma-separated list of accepted status codes for valid links
            # -m, --max-redirects <MAX_REDIRECTS>

            # 'build': the site directory to check
            # './*.md': all markdown files in the root directory
          args: -E -i -n -t 45 --max-concurrency 64 -a 429,401,403 -m 10 -- 'build' '*.md'
          output: out.md
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Broken Link Detected
          content-filepath: out.md
#          assignees: xxx(GitHub ID)
